enum SizesResponsive {
  XsSmall = "0.15rem",
  SmSmaller = "0.25rem",
  MdSmall = "0.3rem",
  Small = "0.5rem",
  LgSmall = "0.625rem",
  XsMedium = "0.75rem",
  SmMedium = "0.8rem",
  MdMedium = "0.9rem",
  Medium = "1rem",
  LgMedium = "1.75rem",
  XsLarge = "2rem",
  SmLarge = "2.25rem",
  MdLarge = "2.5rem",
  Large = "2.75rem",
  LgLarge = "3rem",
  XsLarger = "3.5rem",
  SmLarger = "3.75rem",
  MdLarger = "4rem",
  Larger = "4.5rem",
  LgLarger = "5rem",
  XLarge = "5.5rem",
  XXLarge = "6rem",
}

export default SizesResponsive;
